
buttons:
	pulp build --to src/Buttons/app.js -m Buttons.Main

textfields:
	pulp build --to src/TextFields/app.js -m TextFields.Main

forms:
	pulp build --to src/Forms/app.js -m Forms.Main

serve:
	python -m SimpleHTTPServer